exec-once = ~/.config/scripts/battery_notify.sh

exec-once = swww-daemon
exec-once = wal -R -n
exec-once = ~/.local/bin/start-quickshell.sh
exec-once = swaync
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = mpd-mpris
exec-once = bash -c "sleep 3 && kdeconnect-indicator"
exec-once = [workspace special silent] kitty --class scratchhapp -e happ
