exec-once = xrdb -merge ~/.Xresources
exec-once = ~/.config/scripts/battery_notify.sh
exec-once = ~/.config/scripts/wifi-autoswitch.sh

exec-once = awww-daemon
exec-once = wal -R -n
exec-once = ~/.local/bin/restore-wallpaper.sh
exec-once = waybar
exec-once = ~/.local/bin/start-quickshell.sh
exec-once = swaync
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = mpd-mpris
exec-once = libinput-gestures
exec-once = bash -c "sleep 3 && nmcli networking connectivity check | grep -q full && kdeconnect-indicator"
exec-once = hypridle
exec-once = ~/.local/bin/hypr-monitor-hz-watch.sh
