bind = SUPER, SPACE, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next

bind = $mod, Return, exec, kitty
bind = $mod SHIFT, RETURN, exec, [float; size 700 400] kitty
bind = $mod, R, exec, qs ipc call launcher toggle
bind = $mod, E, exec, thunar
bind = $mod, Q, killactive
bind = $mod, C, togglefloating
bind = $mod, W, exec, qs ipc call wallpaper toggle
bind = $mod SHIFT, W, exec, ~/.config/scripts/random-wallpaper.sh
bind = $mod, L, exec, hyprlock
bind = $mod, A, exec, qs ipc call dashboard toggle
bind = $mod, M, exec, qs ipc call music toggle
bind = $mod, F, fullscreen

bind = $mod, Left, movefocus, l
bind = $mod, Down, movefocus, d
bind = $mod, Up, movefocus, u
bind = $mod, Right, movefocus, r

bind = $mod SHIFT, Left, movewindow, l
bind = $mod SHIFT, Down, movewindow, d
bind = $mod SHIFT, Up, movewindow, u
bind = $mod SHIFT, Right, movewindow, r

binde = $mod CTRL, Left, resizeactive, -20 0
binde = $mod CTRL, Right, resizeactive, 20 0
binde = $mod CTRL, Up, resizeactive, 0 -20
binde = $mod CTRL, Down, resizeactive, 0 20

bind = $mod, Tab, cyclenext
bind = $mod SHIFT, Tab, cyclenext, prev

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1
		
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

bind = $mod, S, togglespecialworkspace
bind = $mod SHIFT, S, movetoworkspace, special

bind = $mod, P, pseudo
bind = $mod, J, togglesplit

bind = SUPER, N, exec, swaync-client -t -sw
bind = SUPER SHIFT, N, exec, swaync-client -C

bind = , Print, exec, ~/.config/scripts/screenshot.sh area
bind = SHIFT, Print, exec, ~/.config/scripts/screenshot.sh full
bind = SUPER SHIFT, Delete, exec, ~/.config/scripts/clear-screenshots.sh

bind = , Menu, exec, ~/.config/scripts/define.sh

bind = $mod SHIFT, R, exec, killall -SIGINT gpu-screen-recorder && notify-send "Recording Stopped"

bindm = $mod, mouse:272, movewindow
bindm = ALT, mouse:272, resizewindow

# Громкость
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Яркость 
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

