source = monitor.conf
source = autostart.conf
source = decoration.conf
source = animations.conf
source = input.conf
source = binds.conf
source = windowrules.conf
source = layerrules.conf




xwayland {
    force_zero_scaling = true
}

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland;xcb
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = GDK_BACKEND,wayland,x11

general {
    extend_border_grab_area = 10
}

gestures {
    workspace_swipe_distance = 200
    workspace_swipe_invert = true
    workspace_swipe_cancel_ratio = 0.15
    workspace_swipe_min_speed_to_force = 10
    workspace_swipe_create_new = false
}

