source = monitor.conf
source = autostart.conf
source = decoration.conf
source = animations.conf
source = input.conf
source = binds.conf
source = windowrules.conf
source = layerrules.conf




general {
    extend_border_grab_area = 10
}

gestures {
    workspace_swipe_invert = true
    workspace_swipe_distance = 200
    gesture = 3, right, dispatcher, exec, hyprctl dispatch workspace -1
    gesture = 3, left, dispatcher, exec, hyprctl dispatch workspace +1
}
