layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar

layerrule = blur on, match:namespace swaync-notification-window

layerrule = ignore_alpha 0.7, match:namespace swaync-notification-window

layerrule = blur on, match:namespace quickshell
layerrule = ignore_alpha 0, match:namespace quickshell

# slurp overlay для скриншотов — без анимации, иначе её хвост попадает в кадр
layerrule = animation none, match:namespace selection


