layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0s, match:namespace waybar

layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window

layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window

layerrule = blur on, match:namespace quickshell
layerrule = ignore_alpha 0, match:namespace quickshell

