windowrule = match:class Lorien, opacity 0.8 1
windowrule = match:class sublime_text, opacity 0.88 1
windowrule = match:class thunar, opacity 0.9 1
windowrule = match:class Thunar, opacity 0.9 1
windowrule = match:class org.pwmt.zathura, opacity 0.9 1
windowrule = match:class firefox, opacity 1.0 1.0

windowrule = match:class mpv, float on
windowrule = match:class mpv, size 640 360
windowrule = match:class mpv, center on
windowrule = match:class mpv, opacity 1.0 1.0

windowrule = match:float yes, center on

windowrule = match:class scratchterm, float on
windowrule = match:class scratchterm, size 85% 70%
windowrule = match:class scratchterm, center on


windowrule = match:class scratchhapp, float on
windowrule = match:class scratchhapp, size 60% 70%
windowrule = match:class scratchhapp, move 20% 5%
windowrule = match:class happ, float on
windowrule = match:class happ, center on
